version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: numpy
    versions:
    - 1.20.0
    - 1.20.2
  - dependency-name: pandas
    versions:
    - 1.2.2
